"""
build_one_piece_data.py — Build One Piece card profiles from a punk-records
scrape (github.com/buhbbl/punk-records, generated by the vegapull tool from
the official One Piece TCG site).

Default source: C:\\punk-records\\english\\cards\\*.json (one file per pack,
each a JSON list of card objects) + C:\\punk-records\\english\\packs.json.
All three paths are overridable via --data-dir / --packs-file / --out-dir,
e.g. to point this at a fixture directory for testing.

Output: {out_dir}/{sku}/profile.json  (one per card)

Design notes (established during recon — see project memory / conversation):

- set_id is derived from the CARD's own ID prefix (e.g. "OP07-091" -> "op07"),
  NOT from which pack/booster JSON file the card was listed under. Two packs
  (569114 "OP14-EB04", 569115 "OP15-EB04") are cross-set reprint boosters that
  each bundle cards from up to 9 different real sets (EB01, EB04, OP06...OP14,
  PRB02, etc.) — grouping by pack would scatter a card's reprints away from
  its real set and corrupt set-completion tracking. Promo cards (packs 569801
  "Other Product Card", 569901 "Promotion card") keep their original set's
  prefix too (e.g. "EB01-003_p2" groups under "eb01"), except genuine
  standalone promos which use their own "P-NNN" prefix -> set_id "p".

- SKU/folder naming follows the mtg-/ygo- precedent (see build_sku_game_map.py,
  build_identifier_lookup.py): prefix with a short game code ("op-") so the
  SKU is globally unambiguous and does NOT need an sku_game_map entry, unlike
  Pokemon's unprefixed SKUs.

- set_metadata.json, sku_game_map.json and identifier_lookup.json are each
  fully REGENERATED by scanning CardsDB (build_set_metadata.py /
  build_sku_game_map.py / build_identifier_lookup.py) — they are not merged
  from precomputed side files. This script therefore only writes CardsDB
  profiles.

SAFETY (2026-09-07): writes are now skip-if-exists by default. An earlier
version wrote profile.json unconditionally for every card in the punk-records
snapshot on every run — including a hardcoded "prices": {} with no
prices_updated key — which silently wiped pricing data populated since by
refresh_onepiece_dotgg_prices.py / backfill_onepiece_dotgg_prices.py on every
existing card a re-run touched, not just genuinely new ones. Default behavior
now only creates profiles that don't exist yet; --force opts into refreshing
an existing card's metadata (name/rarity/effect/etc. from fresher punk-records
data), but prices/prices_updated are ALWAYS carried forward from the existing
file regardless of --force — see the price-preserving write below, which is
the actual fix (skip-if-exists alone would prevent today's bug, but the
merge makes the whole class of bug structurally impossible even if a future
change bypasses the skip gate).

Usage:
    python build_one_piece_data.py                          # all sets, create-only
    python build_one_piece_data.py --set-id op17              # just OP17, create-only
    python build_one_piece_data.py --set-id op17 --force       # OP17, refresh existing metadata (prices always preserved)
    python build_one_piece_data.py --set-id op16,op17          # comma-separated also accepted
    python build_one_piece_data.py --data-dir X --packs-file Y --out-dir Z   # point at a fixture
"""

import argparse
import json
import re
from pathlib import Path

DEFAULT_PUNK_DATA = Path(r"C:\punk-records\english\cards")
DEFAULT_PUNK_PACKS = Path(r"C:\punk-records\english\packs.json")
DEFAULT_CARDSDB_OP = Path(r"C:\CardsDB\onepiece")


def normalize_label(label: str) -> str:
    """'OP-07' -> 'op07', 'OP14-EB04' -> 'op14eb04'"""
    return re.sub(r"[^a-z0-9]", "", label.lower())


def _load_packs(packs_path: Path) -> dict:
    """Return {set_id: display_name}. Tolerant of packs.json being EITHER a
    JSON object keyed by pack id OR a JSON array of pack objects -- this
    script never reads a pack's own id/key either way (only title_parts /
    raw_title), so supporting both shapes is a pure container-shape
    detection, not a field-mapping change."""
    raw = json.loads(packs_path.read_text(encoding="utf-8"))
    pack_iter = raw.values() if isinstance(raw, dict) else raw

    set_name_by_id = {}
    for pack in pack_iter:
        if not isinstance(pack, dict):
            continue
        tp = pack.get("title_parts") or {}
        label = tp.get("label")
        if not label:
            continue
        set_id = normalize_label(label)
        title = tp.get("title") or pack.get("raw_title") or set_id.upper()
        set_name_by_id[set_id] = title
    return set_name_by_id


def _load_cards(data_dir: Path) -> tuple:
    """Returns (all_cards, malformed_files). A malformed/unreadable pack file
    (bad JSON, or valid JSON that isn't a list) is skipped and reported, not
    fatal -- one bad file can't take down the whole run."""
    all_cards = []
    malformed_files = []
    for data_file in sorted(data_dir.glob("*.json")):
        try:
            cards = json.loads(data_file.read_text(encoding="utf-8"))
        except Exception as e:
            malformed_files.append(f"{data_file.name}: {e}")
            continue
        if isinstance(cards, list):
            all_cards.extend(cards)
        else:
            malformed_files.append(f"{data_file.name}: not a JSON list (got {type(cards).__name__})")
    return all_cards, malformed_files


def _parse_set_id_arg(raw_values) -> set:
    """--set-id accepts both repeatable flags and comma-separated values,
    e.g. --set-id op16 --set-id op17  OR  --set-id op16,op17  OR both mixed."""
    only_sets = set()
    for raw in raw_values:
        for piece in raw.split(","):
            piece = piece.strip().lower()
            if piece:
                only_sets.add(piece)
    return only_sets


def main():
    parser = argparse.ArgumentParser(
        description="Build/refresh One Piece CardsDB profiles from a punk-records scrape.")
    parser.add_argument("--data-dir", type=Path, default=DEFAULT_PUNK_DATA,
                         help=f"directory of per-pack *.json card files (default: {DEFAULT_PUNK_DATA})")
    parser.add_argument("--packs-file", type=Path, default=DEFAULT_PUNK_PACKS,
                         help=f"packs.json path (default: {DEFAULT_PUNK_PACKS})")
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_CARDSDB_OP,
                         help=f"CardsDB/onepiece output directory (default: {DEFAULT_CARDSDB_OP})")
    parser.add_argument("--set-id", action="append", default=None,
                         help="only process this set id (e.g. op17). Repeatable "
                              "(--set-id op16 --set-id op17) or comma-separated "
                              "(--set-id op16,op17), or both. Omit for all sets (default).")
    parser.add_argument("--force", action="store_true",
                         help="re-process existing profiles too (metadata refresh from "
                              "fresh punk-records data) -- prices/prices_updated are "
                              "always preserved regardless of this flag")
    args = parser.parse_args()

    only_sets = _parse_set_id_arg(args.set_id) if args.set_id else None

    set_name_by_id = _load_packs(args.packs_file)
    all_cards, malformed_files = _load_cards(args.data_dir)

    print(f"Loaded {len(all_cards)} card entries from {args.data_dir}")
    if malformed_files:
        print(f"  [WARN] {len(malformed_files)} malformed/unreadable pack file(s):")
        for m in malformed_files[:20]:
            print(f"    {m}")
    if only_sets is not None:
        print(f"Scoped to set(s): {sorted(only_sets)}")

    args.out_dir.mkdir(parents=True, exist_ok=True)

    stats = {
        "created": 0, "updated": 0, "skipped_existing": 0,
        "skipped_out_of_scope": 0, "duplicates": 0, "errors": 0,
    }
    seen_ids = set()
    sets_seen = set()
    per_set = {}

    def _bump(set_id, key):
        d = per_set.setdefault(set_id, {"created": 0, "updated": 0, "skipped_existing": 0})
        d[key] += 1

    for card in all_cards:
        try:
            card_id = card.get("id")
            if not card_id:
                stats["errors"] += 1
                continue
            if card_id in seen_ids:
                stats["duplicates"] += 1
                continue
            seen_ids.add(card_id)

            set_id, sep, card_number = card_id.partition("-")
            set_id = set_id.lower()
            if not sep or not card_number:
                print(f"  [SKIP] unparseable id (no hyphen): {card_id!r}")
                stats["errors"] += 1
                continue

            # --set-id filtering happens HERE, after deriving the card's own
            # set_id -- not at the file-glob level. Cross-set reprint packs
            # (OP14-EB04 etc.) bundle cards from multiple real sets into one
            # file, so a --set-id run still scans every pack file; only the
            # per-card write decision is scoped. Cheap: parsing is fast, the
            # per-card work is what --set-id is actually saving.
            if only_sets is not None and set_id not in only_sets:
                stats["skipped_out_of_scope"] += 1
                continue

            sets_seen.add(set_id)
            set_name = set_name_by_id.get(set_id, set_id.upper())

            img_url = card.get("img_full_url", "") or ""
            img_clean = img_url.split("?")[0]

            sku = f"op-{set_id}-{card_number}"
            card_dir = args.out_dir / sku
            profile_path = card_dir / "profile.json"

            had_existing_file = profile_path.exists()

            if had_existing_file and not args.force:
                stats["skipped_existing"] += 1
                _bump(set_id, "skipped_existing")
                continue

            existing_profile = None
            if had_existing_file:  # implies --force, since the branch above already returned otherwise
                try:
                    existing_profile = json.loads(profile_path.read_text(encoding="utf-8"))
                except Exception as e:
                    print(f"  [WARN] existing profile unreadable, cannot carry prices forward, "
                          f"treating as empty: {sku}: {e}")
                    stats["errors"] += 1
                    existing_profile = None

            profile = {
                "api_id": card_id,
                "name": card.get("name", ""),
                "card_number": card_number,
                "set_id": set_id,
                "set_name": set_name,
                "category": "ONEPIECE",
                "card_category": card.get("category", ""),
                "rarity": card.get("rarity", ""),
                "colors": card.get("colors", []),
                "types": card.get("types", []),
                "cost": card.get("cost"),
                "power": card.get("power"),
                "counter": card.get("counter"),
                "attributes": card.get("attributes", []),
                "effect": card.get("effect", ""),
                "trigger": card.get("trigger"),
                "set_era": "",
                "language": "EN",
                "edition": "",
                "img_url": img_clean,
                # PRICE-PRESERVING WRITE — the actual fix for the price-wipe
                # bug. NEVER hardcode "prices" here. A genuinely new card has
                # no price yet, so {} is correct. An existing card (only
                # reachable under --force) has its prices/prices_updated
                # carried forward from its current profile.json, UNCHANGED,
                # regardless of --force -- --force refreshes metadata
                # (name/rarity/effect/etc.) only, it must never touch
                # pricing. This invariant holds even if the existing file
                # was unreadable (existing_profile is None above): falling
                # back to {} there is the same safe default as "genuinely
                # new", not a wipe of anything we could actually read.
                "prices": (existing_profile or {}).get("prices", {}),
            }
            if existing_profile and "prices_updated" in existing_profile:
                profile["prices_updated"] = existing_profile["prices_updated"]

            card_dir.mkdir(parents=True, exist_ok=True)
            profile_path.write_text(
                json.dumps(profile, ensure_ascii=False, indent=2),
                encoding="utf-8",
            )

            if had_existing_file:
                stats["updated"] += 1
                _bump(set_id, "updated")
            else:
                stats["created"] += 1
                _bump(set_id, "created")
        except Exception as e:
            stats["errors"] += 1
            print(f"  [ERROR] {card.get('id', '?') if isinstance(card, dict) else '?'!r}: {e}")

    print(f"\n=== Summary ===")
    print(f"Created                : {stats['created']}")
    print(f"Updated (--force only) : {stats['updated']}")
    print(f"Skipped (existing)     : {stats['skipped_existing']}")
    if only_sets is not None:
        print(f"Skipped (out of --set-id scope) : {stats['skipped_out_of_scope']}")
    print(f"Duplicates             : {stats['duplicates']}")
    print(f"Errors                 : {stats['errors']}")
    print(f"Malformed pack files   : {len(malformed_files)}")
    print(f"Distinct sets touched  : {len(sets_seen)}")
    unnamed = sorted(s for s in sets_seen if s not in set_name_by_id)
    if unnamed:
        print(f"Sets with no dedicated pack label (name falls back to uppercase set_id): {unnamed}")

    if per_set:
        print("\nPer-set breakdown:")
        for set_id in sorted(per_set):
            d = per_set[set_id]
            print(f"  {set_id}: created={d['created']} updated={d['updated']} skipped_existing={d['skipped_existing']}")

    print(
        "\nNext step: build_one_piece_images.py to download card images "
        "(front.png per profile, matching the other verticals' layout)."
    )


if __name__ == "__main__":
    main()
