"""
build_one_piece_data.py — Build One Piece card profiles from the punk-records
scrape at C:\\punk-records\\english\\data\\*.json + packs.json.

Output: C:\\CardsDB\\onepiece\\{sku}\\profile.json  (one per card)

Design notes (established during recon — see project memory / conversation):

- set_id is derived from the CARD's own ID prefix (e.g. "OP07-091" -> "op07"),
  NOT from which pack/booster JSON file the card was listed under. Two packs
  (569114 "OP14-EB04", 569115 "OP15-EB04") are cross-set reprint boosters that
  each bundle cards from up to 9 different real sets (EB01, EB04, OP06...OP14,
  PRB02, etc.) — grouping by pack would scatter a card's reprints away from
  its real set and corrupt set-completion tracking. Promo cards (packs 569801
  "Other Product Card", 569901 "Promotion card") keep their original set's
  prefix too (e.g. "EB01-003_p2" groups under "eb01"), except genuine
  standalone promos which use their own "P-NNN" prefix -> set_id "p".

- SKU/folder naming follows the mtg-/ygo- precedent (see build_sku_game_map.py,
  build_identifier_lookup.py): prefix with a short game code ("op-") so the
  SKU is globally unambiguous and does NOT need an sku_game_map entry, unlike
  Pokemon's unprefixed SKUs.

- set_metadata.json, sku_game_map.json and identifier_lookup.json are each
  fully REGENERATED by scanning CardsDB (build_set_metadata.py /
  build_sku_game_map.py / build_identifier_lookup.py) — they are not merged
  from precomputed side files. This script therefore only writes CardsDB
  profiles. Wiring "onepiece"/"ONEPIECE" into those three builder scripts
  (and app.py/api_routes.py/ocr_confirm.py, which hardcode
  POKEMON/MTG/YUGIOH throughout) is separate follow-up work.

Run: python build_one_piece_data.py
"""

import json
import re
from pathlib import Path

PUNK_DATA = Path(r"C:\punk-records\english\data")
PUNK_PACKS = Path(r"C:\punk-records\english\packs.json")
CARDSDB_OP = Path(r"C:\CardsDB\onepiece")


def normalize_label(label: str) -> str:
    """'OP-07' -> 'op07', 'OP14-EB04' -> 'op14eb04'"""
    return re.sub(r"[^a-z0-9]", "", label.lower())


def main():
    packs = json.loads(PUNK_PACKS.read_text(encoding="utf-8"))

    # set_id (derived from card IDs, e.g. "op07") -> display name, sourced
    # from whichever pack's own label normalizes to that exact set_id.
    set_name_by_id = {}
    for pack in packs.values():
        tp = pack.get("title_parts") or {}
        label = tp.get("label")
        if not label:
            continue
        set_id = normalize_label(label)
        title = tp.get("title") or pack.get("raw_title") or set_id.upper()
        set_name_by_id[set_id] = title

    all_cards = []
    for data_file in sorted(PUNK_DATA.glob("*.json")):
        cards = json.loads(data_file.read_text(encoding="utf-8"))
        if isinstance(cards, list):
            all_cards.extend(cards)

    print(f"Loaded {len(all_cards)} card entries from {PUNK_DATA}")

    CARDSDB_OP.mkdir(parents=True, exist_ok=True)

    seen_ids = set()
    duplicates = 0
    written = 0
    sets_seen = set()

    for card in all_cards:
        card_id = card.get("id")
        if not card_id:
            continue
        if card_id in seen_ids:
            duplicates += 1
            continue
        seen_ids.add(card_id)

        set_id, sep, card_number = card_id.partition("-")
        set_id = set_id.lower()
        if not sep or not card_number:
            print(f"  [SKIP] unparseable id (no hyphen): {card_id!r}")
            continue
        sets_seen.add(set_id)

        set_name = set_name_by_id.get(set_id, set_id.upper())

        img_url = card.get("img_full_url", "") or ""
        img_clean = img_url.split("?")[0]

        profile = {
            "api_id": card_id,
            "name": card.get("name", ""),
            "card_number": card_number,
            "set_id": set_id,
            "set_name": set_name,
            "category": "ONEPIECE",
            "card_category": card.get("category", ""),
            "rarity": card.get("rarity", ""),
            "colors": card.get("colors", []),
            "types": card.get("types", []),
            "cost": card.get("cost"),
            "power": card.get("power"),
            "counter": card.get("counter"),
            "attributes": card.get("attributes", []),
            "effect": card.get("effect", ""),
            "trigger": card.get("trigger"),
            "set_era": "",
            "language": "EN",
            "edition": "",
            "img_url": img_clean,
            "prices": {},
        }

        sku = f"op-{set_id}-{card_number}"
        card_dir = CARDSDB_OP / sku
        card_dir.mkdir(parents=True, exist_ok=True)
        (card_dir / "profile.json").write_text(
            json.dumps(profile, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
        written += 1

    print(f"\nWritten {written} profiles to {CARDSDB_OP}")
    print(f"Skipped {duplicates} duplicate card ID(s) (same id listed under multiple packs)")
    print(f"Distinct sets: {len(sets_seen)}")
    unnamed = sorted(s for s in sets_seen if s not in set_name_by_id)
    if unnamed:
        print(f"Sets with no dedicated pack label (name falls back to uppercase set_id): {unnamed}")

    print(
        "\nNext step: build_one_piece_images.py to download card images "
        "(front.png per profile, matching the other verticals' layout)."
    )
    print(
        "Before this vertical can be indexed/matched, 'onepiece'/'ONEPIECE' "
        "still needs wiring into build_set_metadata.py, build_sku_game_map.py "
        "and build_identifier_lookup.py (all three currently hardcode "
        "pokemon/mtg/yugioh only) — that's separate follow-up work."
    )


if __name__ == "__main__":
    main()
